# Dependencies
highlighter:      pygments
markdown:         kramdown
kramdown:
   input:         GFM  # Enable GitHub Flavored Markdown (fenced code blocks)

# Permalinks
permalink:        pretty
#relative_permalinks: true  # no longer supported on Jekyll 3.x

# Setup
title:            '( . .)Ï†__'
tagline:          'Open thoughts on data...'
description:      'Pitch me a project if you have an idea, I would love to talk to you about it.'
url:              http://jjwesner.github.io
baseurl:          /

author:
  name:           'Janet Wesner'
  url:            https://twitter.com/lolatu2
  email:          janet.wesner@outlook.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jjwesner
