# Dependencies
highlighter:      rouge
markdown:         kramdown
kramdown:
   input:         GFM  # Enable GitHub Flavored Markdown (fenced code blocks)

# Permalinks
permalink:        pretty

# Setup
title:            "( . .)Ï†__"
tagline:          "Open thoughts on data..."
description:      "Pitch me a project if you have an idea. I'll respond if you're excited."
url:              http://yahwes.github.io
baseurl:          
paginate:         5

author:
  name:           'Janet Wesner'
  url:            https://twitter.com/lolatu2
  email:          janet.wesner@outlook.com

# Assets
sass:
  style:            :compressed
 
# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/yahwes

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Exclude -- removes blog portion
exclude:
  - CNAME
  - index.html
